package edu.just.mashoora.constants;

public enum ELawTypes {
    CIVIL_LAW,
    COMMERCIAL_LAW,
    INTERNATIONAL_LAW,
    CRIMINAL_LAW,
    ADMINISTRATIVE_AND_FINANCE_LAW,
    CONSTITUTIONAL_LAW,
    PRIVATE_INTERNATIONAL_LAW,
    PROCEDURAL_LAW
}
